whiteboard/src/IndexPage.tsx
- adjust i18n params in Indexpages.tsx
=> adjust i18n params

packages/oss-upload-button/package.json, packages/oss-upload-button/src/index.tsx, whiteboard/package.json, whiteboard/src/WhiteboardPage.tsx
- update oss-upload-button component version
=> feat: add i18n to oss-upload-button component

packages/preview-controller/src/index.tsx
=> fix(preview-controller): fix component render issue, close #65.

packages/oss-upload-button/src/index.tsx
Co-authored-by: hyrious <hyrious@outlook.com>
=> feat: enable upload buttons though props

packages/oss-drop-upload/package.json, packages/oss-drop-upload/src/index.tsx, whiteboard/package.json, whiteboard/src/AppRoutes.tsx, whiteboard/src/FloatLink.less, whiteboard/src/FloatLink.tsx, whiteboard/src/IndexPage.tsx, whiteboard/src/ReplayPage.tsx, whiteboard/src/SwitchLanguage.tsx, whiteboard/src/WhiteboardPage.tsx, whiteboard/src/apiMiddleware/RoomOperator.ts, whiteboard/src/components/ExitButtonPlayer.tsx, whiteboard/src/components/SwitchRegion.less, whiteboard/src/components/SwitchRegion.tsx, whiteboard/src/region.ts
@Cheerego7 publish @netless/oss-drop-upload 0.0.8 plz.
=> feat: add region

whiteboard/src/WhiteboardPage.tsx
=> fix: add region

packages/tool-box/package.json, packages/tool-box/src/index.tsx
=> fix(tool-box): fix ToolBox component missing without customerComponent

packages/white-video-plugin/package.json, packages/white-video-plugin/src/WhiteVideoPlugin.tsx, packages/white-video-plugin/src/index.less, whiteboard/package.json
=> fix video plugin style

packages/oss-upload-button/package.json, packages/oss-upload-button/src/index.tsx, whiteboard/package.json
- upgrade oss-upload-button to v0.1.13
=> fix(oss-upload-button): fix possible upload failure with dynamic pptx

packages/white-audio-plugin/package.json, packages/white-audio-plugin/src/WhiteAudioPlugin.tsx, packages/white-video-plugin/package.json, packages/white-video-plugin/src/WhiteVideoPlugin.tsx, whiteboard/package.json, whiteboard/src/IndexPage.tsx, whiteboard/src/ReplayPage.tsx, whiteboard/src/ReplayVideoPage.tsx, yarn.lock
- fix(mobx): import from sdk
- chore: bump plugins version
wait for white-web-sdk@2.12.13 release.
@Cheerego7 publish the 2 plugins plz.
=> fix: mobx version conflict

packages/tool-box/package.json, packages/tool-box/src/index.tsx, whiteboard/package.json
@Cheerego7 publish toolbox 0.0.11 plz
=> fix: tool-box type error

packages/oss-upload-button/package.json, packages/oss-upload-manager/package.json, packages/oss-upload-manager/src/index.ts, whiteboard/package.json
- upgrade oss-upload-manager to v1.1.10
- upgrade oss-upload-button to v0.1.15
=> feat(upload-manager): add folder parameter in uploadImageFilesArray

packages/oss-upload-button/package.json, packages/oss-upload-button/src/index.tsx, whiteboard/package.json
- upgrade oss-upload-button to v0.1.16
=> feat(oss-upload-button): add folder parameter in uploadImageFiles

packages/oss-upload-button/package.json, packages/oss-upload-button/src/index.tsx, whiteboard/package.json
=> feat(oss-upload-button): add folder parameter and upgrade version

packages/video-js-plugin/package.json, packages/video-js-plugin/scripts/build.js, packages/video-js-plugin/src/VideoJsPlugin.tsx, packages/video-js-plugin/tsconfig.json, whiteboard/package.json
- refactor(video-js-plugin): simplify code
- refactor(video-js-plugin): add iife output
- refactor(video-js-plugin): minify css
- refactor(video-js-plugin): emit declarations
=> refactor video-js-plugin

packages/docs-center/README.md, packages/docs-center/package.json, packages/docs-center/src/index.tsx, packages/video-js-plugin/package.json, packages/video-js-plugin/scripts/build.js, whiteboard/package.json, whiteboard/src/WhiteboardPage.tsx
- fix(docs-center): error scene path
- refactor(video-js-plugin): change cjs output name
=> fix(docs-center): error scene path

packages/docs-center/package.json, packages/docs-center/src/index.tsx, whiteboard/package.json
- fix(docs-center): logic bugs
- chore: bump version
=> fix(docs-center): logic bugs

packages/video-js-plugin/package.json, packages/video-js-plugin/src/VideoJsPlugin.tsx, packages/video-js-plugin/src/types.ts, whiteboard/package.json
chore(video-js-plugin): release 0.1.7
=> fix(video-js-plugin): support "host" identity

packages/video-js-plugin/README.md, packages/video-js-plugin/package.json, packages/video-js-plugin/src/VideoJsPlugin.tsx, packages/video-js-plugin/src/types.ts
=> feat: add `hideMuteAlert` in `video.js` plugin context settings

packages/white-video-plugin/package.json, packages/white-video-plugin/src/index.less, whiteboard/package.json
- fix(video-plugin): incorrect poster z-index
- chore: bump version
=> fix video plugin ios poster

packages/oss-upload-button/package.json, packages/oss-upload-manager/package.json, packages/oss-upload-manager/src/index.ts, whiteboard/package.json
- upgrade oss-upload-button version to 0.2.1
- upgrade oss-upload-manager version to 1.2.1
=> refactor(oss-upload-manager): change check progress timeout value

whiteboard/package.json, whiteboard/src/CreatePage.tsx, whiteboard/src/appToken.ts, yarn.lock
- chore(package): upgrade @netless/iframe-bridge to 2.1.6
=> feat(whiteboard): add new h5Demo URL

packages/tool-box/package.json, packages/tool-box/src/index.tsx, whiteboard/package.json, whiteboard/src/WhiteboardPage.tsx
[@netless/tool-box@0.1.6](https://www.npmjs.com/package/@netless/tool-box) has been released.
=> feat(tool-box): add hotkey in tool tip

packages/oss-upload-button/src/index.tsx, packages/oss-upload-manager/src/fetch-middleware.ts, packages/oss-upload-manager/src/index.ts
Requires https://github.com/duty-os/token-server/pull/14
=> fix: support static convert pptx files
